{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mongo-pv
spec:
{{- if not .Values.persistentVolume.storageclass.isPureDefault -}}
  storageClassName: mongo
{{- else }}
  annotations:
    storageclass.kubernetes.io/is-default-class: true
{{- end }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /db/mongo
{{- end }}