# Default values for eoloserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent

# Network policies
security:
  enabled: true

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false
  hosts:
    host: cluster-ip
    paths:
    - path: /
    - path: /toposervice/

# Persistent volumes
persistentVolume:
  enabled: true
  mysql:
    storageclass: mysql
    path: /db/mysql
  mongo:
    storageclass: mongo
    path: /db/mongo
  rabbit:
    storageclass: rabbit
    path: /db/rabbitmq

mysql:
  image: mysql
  tag: 8.0.28
  env:
    password: password
    database: eoloplantsDB

mongodb:
  image: mongo
  tag: 5.0.6-focal
  env:
    user: root
    password: password
    database: eoloplantsDB

rabbitmq:
  image: rabbitmq
  tag: 3.9-management
  env:
    defaultUser: root
    defaultPass: password

#codeurjc/planner:v1.0
#huertaslopez/i.huertas.2021-v.martinp.2021-planner:2.0.0
planner: 
  image: huertaslopez/i.huertas.2021-v.martinp.2021-planner
  tag: 2.0.0

server:
  image: codeurjc/server
  tag: v1.0

toposervice:
  image: codeurjc/toposervice
  tag: v1.0
  ports:
    containerPort: 8181

weatherservice:
  image: codeurjc/weatherservice
  tag: v1.0
  env:
    port: 9090