# Default values for eoloserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent

# Network policies
security:
  enabled: true

service:
  type: NodePort #NodePort
  port: 80

ingress:
  enabled: false
  hosts:
    host: cluster-ip

# Persistent volumes
persistentVolume:
  enabled: true #false creación por defecto
  mysql:
    storageclass: mysql
  mongo:
    storageclass: mongo
  rabbit:
    storageclass: rabbit
    
planner: #codeurjc/planner:v1.0
  image: codeurjc/planner
  tag: v1.0

server: #codeurjc/server:v1.0
  image: codeurjc/server
  tag: v1.0

toposervice: #codeurjc/toposervice:v1.0
  image: codeurjc/toposervice
  tag: v1.0

weatherservice: #codeurjc/weatherservice:v1.0
  image: codeurjc/weatherservice
  tag: v1.0